# oauth配置
security:
  oauth2:
    resource:
      prefer-token-info: false
      jwt:
        key-value: M3NvbmdzaHUuY29t
      user-info-uri: http://${maven_docker.ip}:7001/seeker/api/user/userInfo
    client:
      client-id: middle
      client-secret: 123456
      access-token-uri: http://${maven_docker.ip}:7777/uaa/oauth/token
      user-authorization-uri: http://${maven_docker.ip}:7777/uaa/oauth/authorize
      grant-type: client_credentials

#securityResource配置（即为spring-application-name,
#  release-whitelist已有默认，此处可不设置，明细配置可参考local.yaml）
resource:
  application:
    resource-id: marvel-message-server

# swagger配置
springfox:
  documentation:
    swagger-ui:
      #生产环境不应启用
      enabled: true
      base-url: /

swagger:
  enabled: true
  info:
    title: 'marvel-message-server'
    description: '惊奇统一消息服务项目'
    license: ''
    license-url: ''
    version: 'v1.0.0'
    contact-name: '安徽贝慕信息科技有限公司'
    contact-url: 'http://www.bim.com'
    contact-email: 'company@bim.com'
    terms-of-service-url: 'http://www.bim.com'

# 日志级别
logging:
  level:
    root: info
    com.ibatis: INFO
    com.bim.marvel.middle.core.dao: DEBUG
    com.baomidou.mybatisplus.core.mapper: DEBUG
    com.bim.marvel.data.config.datasource: DEBUG

feign:
  hystrix:
    enabled: false
  httpclient:
    connection-timeout: 10000
  okhttp:
    enabled: true
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000