#多网卡配置
#  cloud:
#    inetutils:
#      use-only-site-local-interfaces: true
#      preferred-networks: ['192.168.1']
#      ignored-interfaces: ['VMware.*','Hyper-V.*']
# oauth配置
security:
  oauth2:
    resource:
      prefer-token-info: false
      jwt:
        key-value: M3NvbmdzaHUuY29t
      user-info-uri: http://127.0.0.1:7001/middle/api/user/userInfo
    client:
      client-id: middle
      client-secret: 123456
      access-token-uri: http://127.0.0.1:7777/uaa/oauth/token
      user-authorization-uri: http://127.0.0.1:7777/uaa/oauth/authorize
      grant-type: client_credentials

resource:
  application:
    resource-id: marvel-message-server
    release-whitelist:
      - "/static/**"
      - "/webjars/**"
      - "/v2/api-docs/**"
      - "/api/user/login"
      - "/web-ui.html"
      - "/api-doc.html"
      - "/swagger-ui.html"
      - "/swagger-ui/**"
      - "/doc.html"

# swagger配置
swagger:
  enabled: true
  info:
    title: 'marvel-message-server'
    description: '惊奇统一消息服务项目'
    license: ''
    license-url: ''
    version: 'v1.0'
    contact-name: '安徽贝慕信息科技有限公司'
    contact-url: 'http://www.bim.com'
    contact-email: 'company@bim.com'
    terms-of-service-url: 'http://www.bim.com'

# 日志级别
logging:
  level:
    root: INFO
    com.bim.marvel.data.config.datasource: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: FULL
  hystrix:
    enabled: false
  httpclient:
    connection-timeout: 10000
  okhttp:
    enabled: true
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000




#短信服务配置
sms:
  log:
    mode: mongodb
    mongodb:
      enabled: true
      url: mongodb://122.51.184.243:27017/admin
  retrieve:
    maxCount: 2
  mq:
    mode: rabbitmq
    rabbitmq:
      host: 122.51.184.243
      port: 5672
      username: sms
      password: sms
      virtualhost: sms
      queue:
        log: LOG
        retrieve: RETRIEVE
        query: QUERY
        send: SEND
      exchange:
        direct:
          retrieve: RETRIEVE
          query: QUERY
          send: SEND
        topic:
          log: LOG
  alisms:
    accessKey: accessKey
    accessSecret: accessSecret
    formatters:
      - { id: 1, signName: 123, templateCode: 123, templateParam: 123, validCodeSize: 4 }
      - { id: 2, signName: 123, templateCode: 123, templateParam: 123, validCodeSize: 6 }